### ISSUE TITLE
Crash at Administration > Users > New user

### ISSUE THREAD

**Issue by IlyaSemenov** [batizhevsky/redmine_pretend#17]
Log in as admin, go to Administration > Users > New users and Redmine will crash:

```
Started GET "/users/new" for 127.0.0.1 at 2016-06-06 14:31:39 +0000
Processing by UsersController#new as HTML
  Current user: semenov (id=5)
  Rendered plugins/redmine_pretend/app/views/user/_pretend_to.html.erb (0.8ms)
  Rendered users/_form.html.erb (3.5ms)
  Rendered users/new.html.erb within layouts/admin (3.9ms)
Completed 500 Internal Server Error in 12ms (ActiveRecord: 5.3ms)

ActionView::Template::Error (No route matches {:action=>"pretend_to", :controller=>"application", :id=>nil} missing required keys: [:id]):
    1: <%= link_to l(:button_pretend), pretend_to_path(@user), :class => 'icon', :method => :post if can_user_pretend_to?(@user)  %>
  plugins/redmine_pretend/app/views/user/_pretend_to.html.erb:1:in `_plugins_redmine_pretend_app_views_user__pretend_to_html_erb__583937039420195089_48353540'
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/users/_form.html.erb:24:in `_app_views_users__form_html_erb__1476297882613763971_48968640'
  app/views/users/new.html.erb:4:in `block in _app_views_users_new_html_erb__350812415081951902_49072120'
  app/helpers/application_helper.rb:1030:in `labelled_form_for'
  app/views/users/new.html.erb:3:in `_app_views_users_new_html_erb__350812415081951902_49072120'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

```
Environment:
  Redmine version                3.2.1.stable
  Ruby version                   2.1.8-p440 (2015-12-16) [x86_64-linux-gnu]
  Rails version                  4.2.5.2
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.8.8
  Darcs                          2.8.4
  Mercurial                      2.8.2
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.8.2
  Filesystem                     
Redmine plugins:
  redmine_pretend                2.0.1
```

`redmine_pretend` is installed from git rev. 65b69fa9773fe5c5748556abf7378a66c97364ce

Temporarily removing the plugin fixes the problem.

**Comment by batizhevsky** [comment]
Fixed in the master branch
