### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by radist** [batizhevsky/redmine_pretend#23]
Вот такое происходит, есть версия что связано с плагином. Включил лог на debug получил вот такое. 

Версия redmint 2.6, прочих подробностей посмотреть не могу, так как не работает.

`Rendered watchers/_watchers.html.erb (4.0ms)
  Rendered issues/show.html.erb within layouts/base (518.7ms)
  Rendered inline template (1.0ms)
  Rendered inline template (1.0ms)
  Rendered plugins/redmine_pretend/app/views/user/_unpretend.html.erb (0.0ms)
  Setting Load (0.2ms)  SELECT `settings`.* FROM `settings` WHERE `settings`.`name` = 'plugin_redmine_finance' LIMIT 1
Completed 500 Internal Server Error in 609.1ms

ActionView::Template::Error (undefined class/module ActionController::Parameters):
    23: <div id="top-menu">
    24:     <div id="account">
    25:         <%= render_menu :account_menu -%>
    26:     </div>
    27:     <%= content_tag('div', "#{l(:label_logged_as)} #{link_to_user(User.current, :format => :username)}".html_safe, :id => 'loggedas') if User.current.logged? %>
    28:     <%= render_menu :top_menu if User.current.logged? || !Setting.login_required? -%>
    29: </div>
  app/models/setting.rb:98:in `value'
  app/models/setting.rb:113:in `[]'
  lib/redmine/menu_manager.rb:199:in `call'
  lib/redmine/menu_manager.rb:199:in `allowed_node?'
  lib/redmine/menu_manager.rb:166:in `block in menu_items_for'
  lib/redmine/menu_manager.rb:165:in `each'
  lib/redmine/menu_manager.rb:165:in `menu_items_for'
  lib/redmine/menu_manager.rb:90:in `render_menu'
  app/views/layouts/base.html.erb:26:in `_app_views_layouts_base_html_erb___4485921708287583568_68565180'
  app/controllers/issues_controller.rb:128:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:125:in `show'
`

**Comment by shipiev** [comment]
В строчке 6 происходит получение настроек модуля redmine_finance. Попробуйте отключить его (переместив из папки plugins в другое место).

**Comment by radist** [comment]
redmine_finance, стоял там год. Сейчас посмотреть не могу, так как обновил редмайн и все плагины, проблема ушла. Но насколько я помню, эта строка с sql запросом, периодически менялась, там могло быть 2 - 3 запроса в логе, перед 500 ошибкой.
