### ISSUE TITLE
Server 500 error : Plugin crash on "no route matches missing required key id"

### ISSUE THREAD

**Issue by rocksit** [batizhevsky/redmine_pretend#26]
Hello,

very usefull your plugin. But for some reasons it does not work for me in
Redmine 3.3.2 + Apache 2.4 + passanger config

for some reason, the plugin crashes on calling it as admin. When I will switch identity and click on your link in user interface I get a web server 500 error.

Error in log is : 

```
Started POST "/admin/pretend_to/3" for 62.216.207.109 at 2017-02-13 19:08:45 +0100
Processing by ApplicationController#pretend_to as HTML
  Parameters: {"authenticity_token"=>"*************************************************************", "id"=>"3"}
  Current user: heilmeierc (id=3)
  Rendered common/error.html.erb within layouts/base (1.3ms)
  Rendered plugins/redmine_pretend/app/views/user/_unpretend.html.erb (8.0ms)
  Rendered plugins/progressive_projects_list/app/views/application/_progressive_sidebar.html.erb (0.1ms)
  Rendered plugins/progressive_projects_list/app/views/application/_progressive_recent_projects.html.erb (0.2ms)
Completed 500 Internal Server Error in 111ms (Views: 77.2ms | ActiveRecord: 21.5ms)

ActionController::UrlGenerationError (No route matches {:action=>"show", :controller=>"users", :id=>nil} missing required keys: [:id]):
  plugins/redmine_pretend/lib/redmine_pretend/application_controller_patch.rb:31:in `pretend_to'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```
It seems that in some ways id wont  find its way to controller ? My Rails knowledge is very poor, could you give me a hint please ?

regards
Peter

**Comment by rocksit** [comment]
I think this error is no more relevant due to actual versions of redmine and ruby make pretend work.
