### ISSUE TITLE
Not support Redmine 5.0.3 

### ISSUE THREAD

**Issue by simonefratini** [batizhevsky/redmine_pretend#37]
Hello,

with this 
```
About your application's environment
Rails version             6.1.7
Ruby version              ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
RubyGems version          3.3.5
Rack version              2.2.4
Middleware                ActionDispatch::HostAuthorization, Rack::ContentLength, Rack::Sendfile, ActionDispatch::Static, ActionDispatch::Executor, ActiveSupport::Cache::Strategy::LocalCache::Middleware, Rack::Runtime, Rack::MethodOverride, ActionDispatch::RequestId, RequestStore::Middleware, ActionDispatch::RemoteIp, Rails::Rack::Logger, ActionDispatch::ShowExceptions, ActionDispatch::DebugExceptions, ActionDispatch::ActionableExceptions, ActionDispatch::Callbacks, ActionDispatch::Cookies, ActionDispatch::Session::CookieStore, ActionDispatch::Flash, ActionDispatch::ContentSecurityPolicy::Middleware, ActionDispatch::PermissionsPolicy::Middleware, Rack::Head, Rack::ConditionalGet, Rack::ETag, Rack::TempfileReaper
Application root          /opt/redmine-5.0.3
Environment               production
Database adapter          mysql2
Database schema version   20220224194639
```

I got error where restart redmine after install plugin
```
App 20644 output: Starting Pretend plugin for RedMine
App 20644 output: Error: The application encountered the following error: uninitialized constant RedminePretend::ApplicationControllerPatch (NameError)
App 20644 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
App 20644 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:135:in `cget'
App 20644 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:169:in `block in actual_eager_load_dir'
App 20644 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
App 20644 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:25:in `each'
App 20644 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:25:in `ls'
App 20644 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:164:in `actual_eager_load_dir'
App 20644 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
App 20644 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:16:in `each'
App 20644 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
App 20644 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
App 20644 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
App 20644 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:296:in `block in eager_load_all'
App 20644 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:294:in `each'
App 20644 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:294:in `eager_load_all'
App 20644 output:     /var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
App 20644 output:     /var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `instance_exec'
App 20644 output:     /var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `run'
App 20644 output:     /var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:61:in `block in run_initializers'
App 20644 output:     /usr/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
App 20644 output:     /usr/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
App 20644 output:     /usr/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
App 20644 output:     /usr/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
App 20644 output:     /usr/lib/ruby/3.0.0/tsort.rb:347:in `each'
App 20644 output:     /usr/lib/ruby/3.0.0/tsort.rb:347:in `call'
App 20644 output:     /usr/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
App 20644 output:     /usr/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
App 20644 output:     /usr/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
App 20644 output:     /var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:60:in `run_initializers'
App 20644 output:     /var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/application.rb:391:in `initialize!'
App 20644 output:     /opt/redmine-5.0.3/config/environment.rb:16:in `<top (required)>'
App 20644 output:     config.ru:3:in `require'
App 20644 output:     config.ru:3:in `block in <main>'
App 20644 output:     /var/lib/gems/3.0.0/gems/rack-2.2.4/lib/rack/builder.rb:125:in `instance_eval'
App 20644 output:     /var/lib/gems/3.0.0/gems/rack-2.2.4/lib/rack/builder.rb:125:in `initialize'
App 20644 output:     config.ru:1:in `new'
App 20644 output:     config.ru:1:in `<main>'
App 20644 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `eval'
App 20644 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 20644 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 20644 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
App 20644 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 20644 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 20644 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2022-11-26 16:16:43.4219 20567/Tc age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /opt/redmine: The application encountered the following error: uninitialized constant RedminePretend::ApplicationControllerPatch (NameError)
  Error ID: 7a7b824d
  Error details saved to: /tmp/passenger-error-Dy5eC0.html
```

**Comment by simonefratini** [comment]
Find a replacement that works for 5.x
https://www.redmine.org/plugins/redmine_impersonate

Thanks for you time
